version: '3'
services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    # override the starting command when this 'tests' service (container) is created
    # where going to make sure is will start by 'npm run test' rather then 'npm run start' (the default cmd as in Dockerfile.dev)
    command: ["npm", "run", "test"]