name: Deploy Multidocker
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - run: docker build -t samitab/react-test -f ./Dockerfile.dev .
      - run: docker run -e CI=true samitab/react-test npm test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react-test-project
          environment_name: Dockerreacttestproject-env
          existing_bucket_name: elasticbeanstalk-us-east-1-564934115017
          region: us-east-1
          version_label: 13456
          deployment_package: deploy.zip
